tasks:
  - name: Dependencies & Dev Server
    init: nvm install 14.18.2 | nvm use 14.18.2 | nvm alias default 14.18.2 | npm ci | npm start

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview

# VSCode Extensions
vscode:
  extensions:
    - vsls-contrib.codetour

# image:
#   file: .gitpod.Dockerfile